export const ERROR_CODES = {
  NETWORK: 'ERR_NETWORK',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',
  NOT_FOUND: 'ERR_NOT_FOUND',
  VALIDATION: 'ERR_VALIDATION',
  SERVER: 'ERR_SERVER',
  UNKNOWN: 'ERR_UNKNOWN',
} as const
